---
title: '2019-03-20'
author: "沈家妤"
date: "3/13/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Create an object with values

```{r}
a <- 2
3 -> b
```

```{r}
65 + b
```

```{r}
c <- 47

65 + c
```

```{r}
c
```

```{r}
`c`
```
#  When to use `

```{r}
`107上學期我的平均成績` <- 92
```

```{r}
學期107我的平均成績 <- 92

```

```{r}
`107上學期我的平均成績`
```

```{r}
107上學期我的平均成績
```

# numeric class

```{r}
class(a)
```

```{r}
a<-5
a2<-5L
```

```{r}
class(a)
```

```{r}
class(a2)
```

# vector

```{r}
aVector<-c(5,6,7)
a2Vector<-c(5L,6L,7L)
```

```{r}
class(a2Vector)
```

```{r}
class(aVector)
```

```{r}
class(a2Vector)
```
```{r}
typeof(studentMajors)
```

```{r}
levels(studentMajors)
```

```{r}
as.integer(studentMajors)
```

```{r}
birthplace <- factor(c('台中','台中','台北','台北','台北'))
birthplace
as.integer(birthplace)
```

```{r}
birthplace <- factor(
  c("台北市","台北市","台中市","台北市","台中市")
)
class(birthplace)
levels(birthplace)
as.integer(birthplace)
```

```{r}
birthDate <- factor(c("台北市","台中市","台北市","台中市","台北市"))
class(birthDate)
as.integer(birthDate)
```

```{r}

```

```{r}
job <- factor(c('doctor','teacher','doctor','doctor'))
job
as.integer(job)
```

```{r}
library(lubridate)
```

dtObject<-ymd_hms("1970-01-01 00:02:53") 
```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)

class(dtObject)

dtObject

typeof(dtObject)

as.double(dtObject)
```

```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```




